# Generated by Django 4.1.2 on 2022-10-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0004_alter_ishgarler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='balnoy',
            field=models.BooleanField(default=True),
        ),
    ]
