# Generated by Django 4.1.2 on 2022-10-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0006_alter_ishgarler_balnoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='balnoy_gornush',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maglumat.rugsatlar'),
        ),
    ]
