# Generated by Django 4.1.2 on 2022-10-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0007_ishgarler_balnoy_gornush'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='balnoy_beyan',
            field=models.TextField(default='salam'),
        ),
    ]
