# Generated by Django 4.1.2 on 2022-10-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0008_ishgarler_balnoy_beyan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='balnoy_beyan',
            field=models.TextField(),
        ),
    ]
