# Generated by Django 4.1.2 on 2022-10-31 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0011_ishgarler_balnoy_sony'),
    ]

    operations = [
        migrations.AddField(
            model_name='wezipeler',
            name='is_basla',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
