# Generated by Django 4.1.2 on 2022-11-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0015_rename_obed_gurat_wezipeler_obed_gutar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='end',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='ishgarler',
            name='start',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
