# Generated by Django 4.1.2 on 2022-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0014_alter_ishgarler_barkod_san'),
    ]

    operations = [
        migrations.CreateModel(
            name='days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
    ]
