# Generated by Django 4.1.2 on 2022-11-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0024_alter_days_options_alter_ishgarler_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
