# Generated by Django 4.1.2 on 2022-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0025_ishgarler_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='activeminut',
            field=models.IntegerField(default=0),
        ),
    ]
