# Generated by Django 4.1.2 on 2022-11-07 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0035_ishgarler_balnoy_wagt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='all_end',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='ishgarler',
            name='all_start',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='ishgarler',
            name='each_end',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ishgarler',
            name='each_start',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
