# Generated by Django 4.1.2 on 2022-11-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0038_kurslar_okuwgunler_dinleyjiler'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='okuwgunler',
            new_name='Dinleyji_Gunler',
        ),
        migrations.RenameModel(
            old_name='days',
            new_name='Isgar_Gunler',
        ),
    ]
