# Generated by Django 4.1.2 on 2022-11-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0039_rename_okuwgunler_dinleyji_gunler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinleyjiler',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maglumat.kurslar'),
        ),
    ]
