# Generated by Django 4.1.2 on 2022-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0043_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ishgarler',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='is_bashlayar',
            field=models.CharField(default='09:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='is_gutaryar',
            field=models.CharField(default='09:00', max_length=5),
        ),
    ]
