# Generated by Django 4.1.2 on 2022-12-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0048_ishgarler_each_end_ishgarler_each_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='is_gutaryar',
            field=models.CharField(default='17:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='obed_bashlayar',
            field=models.CharField(default='13:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='obed_gutaryar',
            field=models.CharField(default='14:00', max_length=5),
        ),
    ]
