# Generated by Django 4.1.2 on 2022-12-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0054_alter_ishgarler_obed_gutaryar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='is_bashlayar',
            field=models.CharField(default='09:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='is_gutaryar',
            field=models.CharField(default='17:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='obed_bashlayar',
            field=models.CharField(default='13:00', max_length=5),
        ),
    ]
