# Generated by Django 4.1.2 on 2023-01-06 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0055_alter_ishgarler_is_bashlayar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ishgarler',
            name='active',
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='each_end',
            field=models.DateField(default=datetime.date(2023, 1, 6)),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='each_start',
            field=models.DateField(default=datetime.date(2023, 1, 6)),
        ),
    ]
