# Generated by Django 4.1.2 on 2023-01-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0056_remove_ishgarler_active_alter_ishgarler_each_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ishgarler',
            name='end',
        ),
        migrations.RemoveField(
            model_name='ishgarler',
            name='start',
        ),
    ]
