# Generated by Django 4.1.2 on 2023-01-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0057_remove_ishgarler_end_remove_ishgarler_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinleyjiler',
            name='end',
        ),
        migrations.RemoveField(
            model_name='dinleyjiler',
            name='start',
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='each_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='each_start',
            field=models.DateField(),
        ),
    ]
