# Generated by Django 4.1.2 on 2023-01-06 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0058_remove_dinleyjiler_end_remove_dinleyjiler_start_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AlterField(
            model_name='dinleyjiler',
            name='barkod_surat',
            field=models.ImageField(blank=True, upload_to='barcode_img_d/'),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='each_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='each_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
