# Generated by Django 4.1.2 on 2023-01-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0060_wezipeler_is_bashlayar_wezipeler_is_gutaryar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='is_bashlayar',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='is_gutaryar',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='obed_bashlayar',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='obed_gutaryar',
            field=models.CharField(max_length=5),
        ),
    ]
