# Generated by Django 4.1.2 on 2023-01-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0062_kurslar_okuw_bashlayar_kurslar_okuw_gutaryar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinleyjiler',
            name='okuw_bashlayar',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='dinleyjiler',
            name='okuw_gutaryar',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='okuw_bashlayar',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='okuw_gutaryar',
            field=models.CharField(max_length=5),
        ),
    ]
