# Generated by Django 4.1.2 on 2023-02-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0023_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='del_info_gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(max_length=10)),
            ],
        ),
    ]
