# Generated by Django 4.1.2 on 2023-02-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0065_alter_del_info_gun_gun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='del_info_gun',
            name='gun',
            field=models.CharField(max_length=10),
        ),
    ]
