# Generated by Django 4.1.2 on 2023-02-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0067_alter_ishgarler_balnoy_bash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='balnoy_bash',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='balnoy_sony',
            field=models.DateField(blank=True),
        ),
    ]
