# Generated by Django 4.1.2 on 2023-02-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0066_alter_del_info_gun_gun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='barkod_surat',
            field=models.ImageField(upload_to='barcode_img/'),
        ),
    ]
