# Generated by Django 4.1.2 on 2023-03-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0074_ishgarler_phone_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='phone_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='wezipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degisli', to='maglumat.wezipeler'),
        ),
    ]
