# Generated by Django 3.2 on 2023-10-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0076_auto_20231026_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toparlar',
            name='san',
        ),
    ]
