# Generated by Django 3.2 on 2023-10-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0077_remove_toparlar_san'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talyplar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
