# Generated by Django 4.1.2 on 2023-11-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0079_talyplar_id_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='del_info_gun',
        ),
    ]
