# Generated by Django 4.1.2 on 2023-11-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0080_delete_del_info_gun'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='days',
            new_name='Talyp_Gunler',
        ),
        migrations.AlterModelOptions(
            name='talyp_gunler',
            options={'ordering': ['-day']},
        ),
    ]
