# Generated by Django 4.1.2 on 2024-02-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0082_alter_talyplar_barkod_surat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=10485760)),
            ],
        ),
        migrations.AlterModelOptions(
            name='talyplar',
            options={'ordering': ['at']},
        ),
        migrations.AlterField(
            model_name='talyplar',
            name='barkod_surat',
            field=models.ImageField(blank=True, upload_to='barcode_img/'),
        ),
    ]
