# Generated by Django 4.1.2 on 2024-02-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0083_deviceid_alter_talyplar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talyplar',
            name='device_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_of_student', to='diplom.deviceid'),
            preserve_default=False,
        ),
    ]
