# Generated by Django 4.1.2 on 2024-02-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0084_talyplar_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talyplar',
            name='device_id',
        ),
    ]
