# Generated by Django 4.1.2 on 2024-02-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0087_alter_deviceid_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talyplar',
            name='barkod_san',
        ),
        migrations.RemoveField(
            model_name='talyplar',
            name='barkod_surat',
        ),
        migrations.AlterField(
            model_name='deviceid',
            name='device_id',
            field=models.CharField(max_length=10485760),
        ),
    ]
