# Generated by Django 4.1.2 on 2022-10-27 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0009_alter_ishgarler_balnoy_beyan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='balnoy_bash',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
