# Generated by Django 4.1.2 on 2022-10-27 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0010_ishgarler_balnoy_bash'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='balnoy_sony',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
