# Generated by Django 4.1.2 on 2022-10-31 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0012_wezipeler_is_basla'),
    ]

    operations = [
        migrations.AddField(
            model_name='wezipeler',
            name='is_gutar',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='wezipeler',
            name='obed_basla',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='wezipeler',
            name='obed_gurat',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
