# Generated by Django 4.1.2 on 2022-10-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0014_alter_ishgarler_barkod_san'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wezipeler',
            old_name='obed_gurat',
            new_name='obed_gutar',
        ),
    ]
