# Generated by Django 4.1.2 on 2022-11-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0016_ishgarler_end_ishgarler_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='end',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='start',
            field=models.CharField(max_length=20),
        ),
    ]
