# Generated by Django 4.1.2 on 2022-11-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0017_alter_ishgarler_end_alter_ishgarler_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ishgarler',
            name='end',
        ),
        migrations.RemoveField(
            model_name='ishgarler',
            name='start',
        ),
    ]
