# Generated by Django 4.1.2 on 2022-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0027_remove_ishgarler_activeminut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='activeminut',
            field=models.IntegerField(default=0),
        ),
    ]
