# Generated by Django 4.1.2 on 2022-11-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0029_ishgarler_activesagat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wezipeler',
            name='is_basla',
        ),
        migrations.RemoveField(
            model_name='wezipeler',
            name='is_gutar',
        ),
        migrations.RemoveField(
            model_name='wezipeler',
            name='obed_basla',
        ),
        migrations.RemoveField(
            model_name='wezipeler',
            name='obed_gutar',
        ),
    ]
