# Generated by Django 4.1.2 on 2022-11-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0036_ishgarler_all_end_ishgarler_all_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='days',
            options={'ordering': ['-day']},
        ),
        migrations.AddField(
            model_name='wezipeler',
            name='san',
            field=models.IntegerField(default=0),
        ),
    ]
