# Generated by Django 4.1.2 on 2022-11-12 11:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0037_alter_days_options_wezipeler_san'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san', models.IntegerField(default=0)),
                ('Kurs_at', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['Kurs_at'],
            },
        ),
        migrations.CreateModel(
            name='okuwgunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='Dinleyjiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('at', models.CharField(max_length=100)),
                ('gelen_wagty', models.JSONField()),
                ('giden_wagty', models.JSONField()),
                ('okuw_bashlayar', models.TimeField(default=datetime.time(9, 0))),
                ('okuw_gutaryar', models.TimeField(default=datetime.time(17, 0))),
                ('start', models.TimeField(default=datetime.time(9, 0))),
                ('end', models.TimeField(default=datetime.time(9, 0))),
                ('barkod_san', models.DecimalField(decimal_places=0, max_digits=13)),
                ('barkod_surat', models.ImageField(blank=True, upload_to='barcode_img/')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maglumat.wezipeler')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
