# Generated by Django 4.1.2 on 2022-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0045_remove_ishgarler_each_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
