# Generated by Django 4.1.2 on 2022-12-26 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0047_remove_ishgarler_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='each_end',
            field=models.DateField(default=datetime.date(2022, 12, 26)),
        ),
        migrations.AddField(
            model_name='ishgarler',
            name='each_start',
            field=models.DateField(default=datetime.date(2022, 12, 26)),
        ),
    ]
