# Generated by Django 4.1.2 on 2022-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0049_alter_ishgarler_is_gutaryar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='each_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='each_start',
            field=models.DateField(),
        ),
    ]
