# Generated by Django 4.1.2 on 2022-12-27 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0051_alter_ishgarler_each_end_alter_ishgarler_each_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='is_bashlayar',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
