# Generated by Django 4.1.2 on 2022-12-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0053_alter_ishgarler_is_gutaryar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='obed_gutaryar',
            field=models.CharField(default='14:00', max_length=5),
        ),
    ]
