# Generated by Django 4.1.2 on 2023-01-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0059_delete_movie_alter_dinleyjiler_barkod_surat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wezipeler',
            name='is_bashlayar',
            field=models.CharField(default='09:00', max_length=5),
        ),
        migrations.AddField(
            model_name='wezipeler',
            name='is_gutaryar',
            field=models.CharField(default='17:00', max_length=5),
        ),
        migrations.AddField(
            model_name='wezipeler',
            name='obed_bashlayar',
            field=models.CharField(default='13:00', max_length=5),
        ),
        migrations.AddField(
            model_name='wezipeler',
            name='obed_gutaryar',
            field=models.CharField(default='14:00', max_length=5),
        ),
    ]
