# Generated by Django 4.1.2 on 2023-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0066_alter_del_info_gun_gun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='balnoy_bash',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='balnoy_sony',
            field=models.DateField(),
        ),
    ]
