# Generated by Django 4.1.2 on 2023-02-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0069_alter_ishgarler_balnoy_bash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='each_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ishgarler',
            name='each_start',
            field=models.DateField(null=True),
        ),
    ]
