# Generated by Django 4.1.2 on 2023-03-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0073_alter_ishgarler_barkod_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishgarler',
            name='phone_address',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
